@startuml

box "mtty"
    participant "メイン"       as main
    participant "バッファ管理" as buffer
end box

activate main

ref over main: 初期化

main -> buffer: BufferInit()
activate buffer

group シリアルポート1向け
    buffer -> buffer: MLibRingBufferInit()
    note left
        シリアルポート1
        読込み用バッファ初期化
    end note

    buffer -> buffer: MLibRingBufferInit()
    note left
        シリアルポート1
        書込み用バッファ初期化
    end note
end group

group シリアルポート2向け
    buffer -> buffer: MLibRingBufferInit()
    note left
        シリアルポート2
        読込み用バッファ初期化
    end note

    buffer -> buffer: MLibRingBufferInit()
    note left
        シリアルポート2
        書込み用バッファ初期化
    end note
end group

main <-- buffer:
deactivate buffer

||20||

@enduml

