@startuml

participant "mvfs\nライブラリ" as libmvfs
box "mtty"
    participant "デバイス\nイベント" as devt
    participant "デバイス\n制御"     as dctrl
    participant "エコー"             as echo
    participant "ターミナル\n制御"   as tctrl
    participant "バッファ\n管理"     as bufmng
end box

activate devt
ref over devt: イベント発行

devt -> dctrl: 読込み( デバイスID, fd )
activate dctrl

loop
    libmvfs <- dctrl: デバイスファイルread( fd )
    activate libmvfs
    libmvfs --> dctrl:
    deactivate libmvfs

    break 読込サイズ == 0
        devt <-- dctrl:
    end

    dctrl -> bufmng: バッファ追加\n    ( デバイスID, データ, 読込みサイズ )
    activate bufmng
    ref over bufmng
        バッファ追加
    end ref
    dctrl <-- bufmng:
    deactivate bufmng

    dctrl -> tctrl: 読込みレディ( デバイスID )
    activate tctrl
    ref over tctrl: 読込みレディ通知
    dctrl <-- tctrl:
    deactivate tctrl

    dctrl -> echo: エコー( fd )
    activate echo
    ref over echo: エコー
    dctrl <-- echo:
    deactivate echo
end

devt <-- dctrl:
deactivate dctrl
||20||

@enduml

