@startuml

participant "mvfs\nライブラリ" as libmvfs
box "mtty"
    participant "デバイス\n制御"   as dctrl
    participant "ターミナル\n制御" as tctrl
end box

activate tctrl
ref over tctrl: ターミナルファイルwrite

dctrl <- tctrl: 書込み( デバイスID, fd )
activate dctrl


opt 書込みサイズ != 0
    libmvfs <- dctrl: デバイスファイル書込み( fd, データ, 書込みサイズ )
    activate libmvfs
    libmvfs --> dctrl:
    deactivate libmvfs
end opt

dctrl --> tctrl:
deactivate dctrl
||20||

@enduml

