@startuml

participant drv as "drv_ns16550"

box "mtty"
    participant devt as "デバイスイベント"
    participant dctrl as "デバイス制御"
    participant buffer as "バッファ管理"
end box

activate devt

ref over devt: イベント発行

devt -> dctrl: DctrlDoWrite( デバイスID, fd )
activate dctrl

dctrl -> buffer: BufferPopForWrite( デバイスID )
activate buffer

ref over buffer: 書込み用バッファ管理

dctrl <-- buffer:
deactivate buffer

opt 書込みサイズ != 0
    drv <<- dctrl: LibMvfsWrite( fd, ... )
    activate drv
    drv --> dctrl:
    deactivate drv
end opt

devt <-- dctrl:
deactivate dctrl
||20||

@enduml

