@startuml

participant "mvfs\nライブラリ" as libmvfs
box "mtty"
    participant "メイン"             as main
    participant "デバイス\nイベント" as devt
    participant "デバイス\n制御"     as dctrl
end box

activate main
ref over main: 制御開始

main -> devt: 制御開始
activate devt

loop
    devt -> devt: 読込み監視FDリスト初期化
    devt -> devt: 読込み監視FDリスト設定( シリアルポート1 )
    devt -> devt: 読込み監視FDリスト設定( シリアルポート2 )

    libmvfs <- devt: デバイスファイル監視
    activate libmvfs
    ...
    libmvfs --> devt:
    deactivate libmvfs

    loop 全監視FD数分
        alt シリアルポート1読込可能
            devt -> dctrl: 読込み(シリアルポート1)
            activate dctrl
            ref over dctrl: 読込み
            devt <-- dctrl:
            deactivate dctrl
        else シリアルポート2読込可能
            devt -> dctrl: 読込み(シリアルポート2)
            activate dctrl
            ref over dctrl: 読込み
            devt <-- dctrl:
            deactivate dctrl
        end alt
    end loop
end loop

main <-- devt:
deactivate devt

@enduml
