@startuml

box "mtty"
    participant "セッション管理" as sess
    participant "ユーザイベント" as uevt
    participant "ユーザ"         as user
end box

activate uevt

ref over uevt: スケジューリング

sess <- uevt: SessDoVfsClose( fd, ... )
activate sess

sess -> sess: MLibListSearchHead()
note left: セッション情報の取得

alt セッション情報有り
    sess -> sess: free()
    note left: セッション情報の解放
    sess ->> user: LibMvfsSendVfsCloseResp( fd, 成功, ... )
else セッション情報無し
    sess ->> user: LibMvfsSendVfsCloseResp( fd, 失敗, ... )
end alt

sess --> uevt:
deactivate sess
||20||

@enduml


