@startuml

box "mtty"
    participant "セッション管理" as sess
    participant "ユーザイベント" as uevt
    participant "ユーザ"         as user
end box

activate uevt

ref over uevt: スケジューリング

sess <- uevt: SessDoVfsOpen( fd, path, ... )
activate sess

break pathがmttyの管理ファイルパスでない
    sess ->> user: LibMvfsSendVfsOpenResp( fd, 失敗, ... )
    sess --> uevt:
end break

sess -> sess: malloc()
note left: セッション情報割り当て

break 割り当て失敗
    sess ->> user: LibMvfsSendVfsOpenResp( fd, 失敗, ... )
    sess --> uevt:
end break

rnote over sess #FFFFFF: セッション情報設定

sess -> sess: MLibListInsertHead()
note left: セッション情報をリストに追加

sess ->> user: LibMvfsSendVfsOpenResp( fd, 成功, ... )

sess --> uevt:
deactivate sess

||20||

@enduml

