@startuml

box "mtty"
    participant "デバイス\n制御" as dctrl
    participant "エコー"         as echo
end box

activate dctrl
ref over dctrl: デバイスファイルread

dctrl -> echo: エコー( デバイスID, データ, データサイズ )
activate echo

loop データサイズ分
    opt 制御コード
        rnote over echo #FFFFFF: 文字変換
    end opt

    dctrl <- echo: 書込み( デバイスID, データ )
    activate dctrl
    ref over dctrl: デバイスファイルwrite
    dctrl --> echo:
    deactivate dctrl
end loop

dctrl <-- echo:
deactivate echo

@enduml

