@startuml

participant kernel
box "mtty"
    participant "メイン"           as main
    participant "バッファ管理"     as buffer
    participant "デバイスイベント" as devt
    participant "セッション管理"   as sess
    participant "ユーザイベント"   as uevt
end box

kernel -> main: main
activate main

group 初期化
    main -> buffer: BufferInit()
    activate buffer
    ref over buffer: 初期化
    main <-- buffer:
    deactivate buffer

    main -> devt: DevtInit()
    activate devt
    ref over devt: 初期化
    main <-- devt:
    deactivate devt

    main -> sess: SessInit()
    activate sess
    ref over sess: 初期化
    main <-- sess:
    deactivate sess

    main -> uevt: UevtInit()
    activate uevt
    ref over uevt: 初期化
    main <-- uevt:
    deactivate uevt
end group

ref over main: 制御開始

@enduml
