@startuml

participant "Mochi\nKernel" as kernel
box "mtty"
    participant "メイン"             as main
    participant "バッファ\n管理"     as bufmng
    participant "デバイス\nイベント" as devt
    participant "ターミナル\n制御"   as tctrl
    participant "セッション\n管理"   as sessmng
    participant "ユーザ\nイベント"   as uevt
end box

kernel -> main: main
activate main

main -> bufmng: 初期化
activate bufmng
ref over bufmng: 初期化
main <-- bufmng:
deactivate bufmng

main -> devt: 初期化
activate devt
ref over devt: 初期化
main <-- devt:
deactivate devt

main -> tctrl: 初期化
activate tctrl
ref over tctrl: 初期化
main <-- tctrl:
deactivate tctrl

main -> sessmng: 初期化
activate sessmng
ref over sessmng: 初期化
main <-- sessmng:
deactivate sessmng

main -> uevt: 初期化
activate uevt
ref over uevt: 初期化
main <-- uevt:
deactivate uevt

ref over main: 制御開始

@enduml
