@startuml

participant kernel
box "mtty"
    participant main
    participant devt as "デバイスイベント"
end box

kernel -> main: 起動
activate main

ref over main: 初期化

group 制御開始
    main -> devt: DevtStart()
    activate devt

    ref over devt: 制御開始

    main <-- devt:
    deactivate devt
end group

@enduml

