@startuml

box "mtty"
    participant "メイン"             as main
    participant "デバイス\nイベント" as devt
end box

activate main
ref over main: 初期化

main -> devt: 制御開始
activate devt

ref over devt
    制御開始
end ref

main <-- devt:
deactivate devt

@enduml

