@startuml

box "mtty"
    participant "バッファ管理"   as buffer
    participant "tty制御"        as tty
    participant "セッション管理" as sess
    participant "ユーザイベント" as uevt
end box
participant "ユーザ" as user

activate uevt

ref over uevt: スケジューリング

tty <- uevt: TtyDoVfsRead( fd, サイズ, ... )
activate tty

tty -> sess: SessConvertFdToId( fd )
activate sess
ref over sess: デバイスID変換
tty <-- sess:
deactivate sess

break 無効デバイスID
    tty ->> user: LibMvfsSendVfsReadResp( fd, 失敗, ... )
    tty --> uevt:
end opt

tty -> tty: malloc( サイズ )
note left: データ領域確保

break データ領域確保失敗
    tty ->> user: LibMvfsSendVfsReadResp( fd, 失敗, ... )
    tty --> uevt:
end opt

buffer <- tty: BufferPopForRead( デバイスID, サイズ, ... )
activate buffer
ref over buffer : バッファ取り出し
buffer --> tty:
deactivate buffer

alt 取り出したサイズが1以上
    tty ->> user: LibMvfsSendVfsReadResp( fd, 成功, データ, ... )
else 取り出したサイズが0
    tty ->> user: LibMvfsSendVfsReadResp( fd, 失敗, ... )
end alt

tty -> tty: free( データ領域 )
note left: データ領域解放

tty --> uevt:
deactivate tty

||20||

@enduml
